import type { PanoramaScene } from "@/types/panorama";

/** 测试用全景图（Three.js 官方示例图，替换为真实校园全景） */
const DEMO_PANO =
  "https://threejs.org/examples/textures/2294472375_24a3b8ef46_o.jpg";

export const MOCK_SCENES: PanoramaScene[] = [
  {
    id: "entrance",
    name: "正门广场",
    slug: "entrance-square",
    category: "entrance",
    description: "东莞理工学院正门广场，校园的起点。每年新生从这里踏入校园，开启大学生活。",
    thumbnail: DEMO_PANO,
    panoramaUrl: DEMO_PANO,
    initialYaw: 0,
    initialPitch: 0,
    order: 1,
    hotspots: [
      {
        id: "to-library",
        type: "navigation",
        yaw: 45,
        pitch: 0,
        icon: "arrow",
        label: "图书馆",
        tooltip: "前往图书馆",
        targetSceneId: "library",
        animation: "pulse",
      },
      {
        id: "to-teaching",
        type: "navigation",
        yaw: -60,
        pitch: 0,
        icon: "arrow",
        label: "教学楼B区",
        tooltip: "前往教学楼",
        targetSceneId: "teaching",
        animation: "pulse",
      },
      {
        id: "info-entrance",
        type: "info",
        yaw: 120,
        pitch: 5,
        icon: "info",
        label: "校门历史",
        tooltip: "了解校门的故事",
        infoContent:
          "## 正门广场\n\n东莞理工学院正门建于1992年，校门设计融合了岭南建筑风格与现代元素。广场面积约5000平方米，是学校举行重大活动的场所。\n\n每年开学典礼、毕业典礼均在此举行。",
        animation: "float",
      },
      {
        id: "to-dormitory",
        type: "navigation",
        yaw: 180,
        pitch: 0,
        icon: "arrow",
        label: "学生宿舍",
        tooltip: "前往宿舍区",
        targetSceneId: "dormitory",
        animation: "pulse",
      },
    ],
  },
  {
    id: "library",
    name: "图书馆大厅",
    slug: "library-hall",
    category: "library",
    description: "图书馆是校园的知识中心，藏书超过200万册，24小时自习室全年开放。",
    thumbnail: DEMO_PANO,
    panoramaUrl: DEMO_PANO,
    initialYaw: 0,
    initialPitch: 0,
    order: 2,
    hotspots: [
      {
        id: "back-entrance",
        type: "navigation",
        yaw: -30,
        pitch: 0,
        icon: "arrow",
        label: "返回正门",
        tooltip: "返回正门广场",
        targetSceneId: "entrance",
        animation: "pulse",
      },
      {
        id: "to-lab",
        type: "navigation",
        yaw: 90,
        pitch: 0,
        icon: "arrow",
        label: "实验楼",
        tooltip: "前往实验楼",
        targetSceneId: "lab",
        animation: "pulse",
      },
      {
        id: "info-library",
        type: "info",
        yaw: -120,
        pitch: 0,
        icon: "info",
        label: "图书馆概况",
        tooltip: "查看图书馆介绍",
        infoContent:
          "## 图书馆\n\n- 建筑面积: 32,000㎡\n- 阅览座位: 4,000+\n- 纸质藏书: 200万+册\n- 电子资源: 100+数据库\n- 开放时间: 07:00-23:00\n- 24小时自习室: 全天开放",
        animation: "float",
      },
    ],
  },
  {
    id: "teaching",
    name: "教学楼B区",
    slug: "teaching-b",
    category: "teaching",
    description: "教学楼B区是智能制造工程学院所在地，拥有智慧教室和实验室。",
    thumbnail: DEMO_PANO,
    panoramaUrl: DEMO_PANO,
    initialYaw: 0,
    initialPitch: 0,
    order: 3,
    hotspots: [
      {
        id: "back-entrance-2",
        type: "navigation",
        yaw: 60,
        pitch: 0,
        icon: "arrow",
        label: "返回正门",
        tooltip: "返回正门广场",
        targetSceneId: "entrance",
        animation: "pulse",
      },
      {
        id: "to-canteen",
        type: "navigation",
        yaw: -90,
        pitch: 0,
        icon: "arrow",
        label: "第一食堂",
        tooltip: "前往食堂",
        targetSceneId: "canteen",
        animation: "pulse",
      },
      {
        id: "info-classroom",
        type: "info",
        yaw: 150,
        pitch: 5,
        icon: "info",
        label: "智慧教室",
        tooltip: "了解智慧教室",
        infoContent:
          "## 教学楼B区\n\n智能制造工程学院教学区，配备：\n- 智慧教室 20间\n- 多媒体教室 15间\n- 学术报告厅 2个\n- 教师办公室\n\n主要承担机械、电子、自动化等专业的教学任务。",
        animation: "float",
      },
    ],
  },
  {
    id: "dormitory",
    name: "学生宿舍区",
    slug: "dormitory-area",
    category: "dormitory",
    description: "学生宿舍区，四人间标准配置，空调、热水、网络全覆盖。",
    thumbnail: DEMO_PANO,
    panoramaUrl: DEMO_PANO,
    initialYaw: 0,
    initialPitch: 0,
    order: 4,
    hotspots: [
      {
        id: "back-entrance-3",
        type: "navigation",
        yaw: 0,
        pitch: 0,
        icon: "arrow",
        label: "返回正门",
        tooltip: "返回正门广场",
        targetSceneId: "entrance",
        animation: "pulse",
      },
      {
        id: "to-canteen-2",
        type: "navigation",
        yaw: -120,
        pitch: 0,
        icon: "arrow",
        label: "第二食堂",
        tooltip: "前往第二食堂",
        targetSceneId: "canteen",
        animation: "pulse",
      },
    ],
  },
  {
    id: "canteen",
    name: "第一食堂",
    slug: "canteen-1",
    category: "canteen",
    description: "第一食堂是校园最大的餐饮中心，可容纳3000人同时就餐。",
    thumbnail: DEMO_PANO,
    panoramaUrl: DEMO_PANO,
    initialYaw: 0,
    initialPitch: 0,
    order: 5,
    hotspots: [
      {
        id: "back-teaching",
        type: "navigation",
        yaw: 90,
        pitch: 0,
        icon: "arrow",
        label: "教学楼B区",
        tooltip: "返回教学楼",
        targetSceneId: "teaching",
        animation: "pulse",
      },
      {
        id: "to-dormitory-2",
        type: "navigation",
        yaw: -45,
        pitch: 0,
        icon: "arrow",
        label: "学生宿舍",
        tooltip: "前往宿舍区",
        targetSceneId: "dormitory",
        animation: "pulse",
      },
      {
        id: "to-sports",
        type: "navigation",
        yaw: -140,
        pitch: 0,
        icon: "arrow",
        label: "体育馆",
        tooltip: "前往体育馆",
        targetSceneId: "sports",
        animation: "pulse",
      },
    ],
  },
  {
    id: "lab",
    name: "实验楼",
    slug: "lab-building",
    category: "lab",
    description: "实验楼汇集机器人实验室、智能制造中心、AUV研发平台。",
    thumbnail: DEMO_PANO,
    panoramaUrl: DEMO_PANO,
    initialYaw: 0,
    initialPitch: 0,
    order: 6,
    hotspots: [
      {
        id: "back-library",
        type: "navigation",
        yaw: -90,
        pitch: 0,
        icon: "arrow",
        label: "图书馆",
        tooltip: "返回图书馆",
        targetSceneId: "library",
        animation: "pulse",
      },
      {
        id: "info-robot",
        type: "info",
        yaw: 45,
        pitch: 0,
        icon: "info",
        label: "机器人实验室",
        tooltip: "查看机器人项目",
        infoContent:
          "## 机器人实验室\n\n- 工业机器人平台 6台\n- 协作机器人 4台\n- AGV移动平台 3台\n- 视觉检测系统\n- ROS开发环境\n\n主要研究方向：机器人控制、机器视觉、人机协作。",
        animation: "float",
      },
      {
        id: "info-auv",
        type: "info",
        yaw: 140,
        pitch: 0,
        icon: "info",
        label: "AUV研发平台",
        tooltip: "查看AUV项目",
        infoContent:
          "## 模块化 AUV 研发平台\n\n- 自主导航系统\n- PID姿态控制\n- 水声通信\n- BMS电池管理\n- 模块化任务载荷\n\n基于STM32+FreeRTOS，面向水下探测与巡检应用。",
        animation: "float",
      },
    ],
  },
  {
    id: "sports",
    name: "体育馆",
    slug: "sports-center",
    category: "sports",
    description: "综合体育馆，含篮球场、羽毛球场、游泳馆、健身房。",
    thumbnail: DEMO_PANO,
    panoramaUrl: DEMO_PANO,
    initialYaw: 0,
    initialPitch: 0,
    order: 7,
    hotspots: [
      {
        id: "back-canteen",
        type: "navigation",
        yaw: 140,
        pitch: 0,
        icon: "arrow",
        label: "第一食堂",
        tooltip: "返回食堂",
        targetSceneId: "canteen",
        animation: "pulse",
      },
      {
        id: "to-landscape",
        type: "navigation",
        yaw: -60,
        pitch: 0,
        icon: "arrow",
        label: "校园湖景",
        tooltip: "前往校园湖景",
        targetSceneId: "landscape",
        animation: "pulse",
      },
    ],
  },
  {
    id: "landscape",
    name: "校园湖景",
    slug: "campus-lake",
    category: "landscape",
    description: "校园中心湖，环湖步道1.2公里，是师生休闲散步的好去处。",
    thumbnail: DEMO_PANO,
    panoramaUrl: DEMO_PANO,
    initialYaw: 0,
    initialPitch: 0,
    order: 8,
    hotspots: [
      {
        id: "back-sports",
        type: "navigation",
        yaw: 60,
        pitch: 0,
        icon: "arrow",
        label: "体育馆",
        tooltip: "返回体育馆",
        targetSceneId: "sports",
        animation: "pulse",
      },
      {
        id: "back-entrance-4",
        type: "navigation",
        yaw: -100,
        pitch: 0,
        icon: "arrow",
        label: "正门广场",
        tooltip: "返回正门广场",
        targetSceneId: "entrance",
        animation: "pulse",
      },
    ],
  },
];

export function getSceneById(id: string): PanoramaScene | undefined {
  return MOCK_SCENES.find((s) => s.id === id);
}

export function getSceneBySlug(slug: string): PanoramaScene | undefined {
  return MOCK_SCENES.find((s) => s.slug === slug);
}
