import type { PanoramaScene } from "@/types/panorama";

/** 本地全景图（实验室实拍） */
const MENWAI = "/panoramas/menwai.jpg";
const ZHONGJIAN = "/panoramas/zhongjian.jpg";
const ZUOBIAN = "/panoramas/zuobian.jpg";
const YOUBIAN = "/panoramas/youbian.jpg";

export const MOCK_SCENES: PanoramaScene[] = [
  {
    id: "entrance",
    name: "实验室门口",
    slug: "entrance-square",
    category: "entrance",
    description: "智能制造创新实验室入口区域，涵盖3D打印、机器人、嵌入式开发等方向。",
    thumbnail: MENWAI,
    panoramaUrl: MENWAI,
    initialYaw: 0,
    initialPitch: 0,
    order: 1,
    hotspots: [
      {
        id: "to-center",
        type: "navigation",
        yaw: 0,
        pitch: 0,
        icon: "arrow",
        label: "中间工位区",
        tooltip: "前往中间工位区",
        targetSceneId: "center-area",
        animation: "pulse",
      },
      {
        id: "to-left",
        type: "navigation",
        yaw: -90,
        pitch: 0,
        icon: "arrow",
        label: "左边工位区",
        tooltip: "前往左边工位区",
        targetSceneId: "left-area",
        animation: "pulse",
      },
      {
        id: "to-right",
        type: "navigation",
        yaw: 90,
        pitch: 0,
        icon: "arrow",
        label: "右边设备区",
        tooltip: "前往右边设备区",
        targetSceneId: "right-area",
        animation: "pulse",
      },
      {
        id: "info-entrance",
        type: "info",
        yaw: 180,
        pitch: 0,
        icon: "info",
        label: "实验室介绍",
        tooltip: "关于智能制造创新实验室",
        infoContent:
          "## 智能制造创新实验室\n\n东莞理工学院智能制造创新实验室成立于2020年，面向智能制造工程专业学生开放。\n\n- 3D打印区: FDM/SLA 打印机 8台\n- 嵌入式开发区: STM32/ESP32/树莓派\n- 机器人平台: 工业机器人、协作机器人\n- AUV研发: 水下机器人测试水池",
        animation: "float",
      },
    ],
  },
  {
    id: "center-area",
    name: "中间工位区",
    slug: "center-workstation",
    category: "lab",
    description: "中间工位区是实验室核心区域，学生日常学习和项目开发的主要场所。",
    thumbnail: ZHONGJIAN,
    panoramaUrl: ZHONGJIAN,
    initialYaw: 0,
    initialPitch: 0,
    order: 2,
    hotspots: [
      {
        id: "back-entrance-c",
        type: "navigation",
        yaw: 180,
        pitch: 0,
        icon: "arrow",
        label: "返回门口",
        tooltip: "返回实验室门口",
        targetSceneId: "entrance",
        animation: "pulse",
      },
      {
        id: "to-left-c",
        type: "navigation",
        yaw: -90,
        pitch: 0,
        icon: "arrow",
        label: "左边工位区",
        tooltip: "前往左边工位区",
        targetSceneId: "left-area",
        animation: "pulse",
      },
      {
        id: "to-right-c",
        type: "navigation",
        yaw: 90,
        pitch: 0,
        icon: "arrow",
        label: "右边设备区",
        tooltip: "前往右边设备区",
        targetSceneId: "right-area",
        animation: "pulse",
      },
      {
        id: "info-center",
        type: "info",
        yaw: 0,
        pitch: 0,
        icon: "info",
        label: "工位区概况",
        tooltip: "查看工位区介绍",
        infoContent:
          "## 中间工位区\n\n实验室核心工作区域，配置：\n- 开发工位 12个\n- 示波器、信号发生器、直流电源\n- 焊接台、热风枪\n- 元器件柜（电阻/电容/传感器/电机驱动）\n\n主要承担日常项目开发和课程实验。",
        animation: "float",
      },
    ],
  },
  {
    id: "left-area",
    name: "左边工位区",
    slug: "left-workstation",
    category: "lab",
    description: "左边工位区 — 嵌入式与IoT开发专区，STM32/ESP32项目集中调试区。",
    thumbnail: ZUOBIAN,
    panoramaUrl: ZUOBIAN,
    initialYaw: 0,
    initialPitch: 0,
    order: 3,
    hotspots: [
      {
        id: "back-entrance-l",
        type: "navigation",
        yaw: 90,
        pitch: 0,
        icon: "arrow",
        label: "返回门口",
        tooltip: "返回实验室门口",
        targetSceneId: "entrance",
        animation: "pulse",
      },
      {
        id: "to-center-l",
        type: "navigation",
        yaw: 90,
        pitch: 0,
        icon: "arrow",
        label: "中间工位区",
        tooltip: "前往中间工位区",
        targetSceneId: "center-area",
        animation: "pulse",
      },
      {
        id: "info-embedded",
        type: "info",
        yaw: 0,
        pitch: 0,
        icon: "info",
        label: "嵌入式开发",
        tooltip: "查看嵌入式项目",
        infoContent:
          "## 嵌入式开发专区\n\n- STM32F401/F407 开发板 10套\n- ESP32 模组 8套\n- Arduino 套件 6套\n- 树莓派 4B 4台\n- 传感器模块: DHT11, MQ135, MPU6050, 超声波\n- 执行器: 舵机、步进电机、直流电机\n\n主要方向：智能温室、AUV控制、VR交互。",
        animation: "float",
      },
    ],
  },
  {
    id: "right-area",
    name: "右边设备区",
    slug: "right-equipment",
    category: "lab",
    description: "右边设备区 — 3D打印与加工区，含FDM/SLA打印机及后处理设备。",
    thumbnail: YOUBIAN,
    panoramaUrl: YOUBIAN,
    initialYaw: 0,
    initialPitch: 0,
    order: 4,
    hotspots: [
      {
        id: "back-entrance-r",
        type: "navigation",
        yaw: -90,
        pitch: 0,
        icon: "arrow",
        label: "返回门口",
        tooltip: "返回实验室门口",
        targetSceneId: "entrance",
        animation: "pulse",
      },
      {
        id: "to-center-r",
        type: "navigation",
        yaw: -90,
        pitch: 0,
        icon: "arrow",
        label: "中间工位区",
        tooltip: "前往中间工位区",
        targetSceneId: "center-area",
        animation: "pulse",
      },
      {
        id: "info-3dprint",
        type: "info",
        yaw: 0,
        pitch: 0,
        icon: "info",
        label: "3D打印设备",
        tooltip: "查看3D打印专区",
        infoContent:
          "## 3D打印与制造区\n\n- FDM打印机 5台 (Creality Ender-3)\n- SLA光固化 2台\n- 耗材: PLA, ABS, PETG, 柔性TPU\n- 后处理: 打磨、喷漆、UV固化\n\n支持学生课程设计和创新项目原型制作。",
        animation: "float",
      },
      {
        id: "info-robot-area",
        type: "info",
        yaw: 180,
        pitch: 0,
        icon: "info",
        label: "机器人平台",
        tooltip: "查看机器人项目",
        infoContent:
          "## 机器人开发平台\n\n- 六轴工业机器人 1台\n- 协作机械臂 2台\n- AGV移动平台 2台\n- 视觉检测系统 (YOLO + OpenCV)\n- ROS2开发环境\n\n主要研究方向：机器人控制、机器视觉、人机协作。",
        animation: "float",
      },
    ],
  },
];

export function getSceneById(id: string): PanoramaScene | undefined {
  return MOCK_SCENES.find((s) => s.id === id);
}

export function getSceneBySlug(slug: string): PanoramaScene | undefined {
  return MOCK_SCENES.find((s) => s.slug === slug);
}
